### PR TITLE
Uninitialized constant Puppet::ModuleTool::ModulefileReader #296,…

### PR DESCRIPTION
**Pull request by rnowosielski**
To stop the bleeding, let's at least check if it exists. In my case, this stopped the error, in favor of a warning about missing version... However my puppet deployment had all the required modules and worked successfully. Nevertheless I am quite new to this so I am not sure if there is some additional work that would need to happen to make it more bulletproof.

### CODE REVIEW

**Comment by jamescarr** [comment]
:+1: 

I dusted off an older project and blew probably about an hour trying to figure this out. Using the above gem I got my puppetfile to install!

**Comment by carlossg** [comment]
The branch `puppet4` is trying to fix the issue, but not yet finished, need to refactor tests

See #296

**Comment by rnowosielski** [comment]
I saw #296 earlier when researching my problems and this is a two-liner I applied in my deployment to stop the bleeding and to be able to continue with my work. If there is an effort to fix it somewhere else that's good. Downgrading puppet is unfortunately not an option for me :(

**Comment by carlossg** [comment]
Fixed in 2.2.0, see #296

**Pull request closed without merging**
