### PR TITLE
Upgrade to puppet_forge 2

### LINKED ISSUE #330: Installing 2.2.1 requires ruby 2.2.2
Due to:
> activesupport requires Ruby version >= 2.2.2

Turns out:
- A: `librarian-puppet 2.2.1` requires `puppet_forge ~> 1.0`
- B: `puppet_forge 1.0.5` requires `her ~> 0.6.8` ([reference](https://github.com/puppetlabs/forge-ruby/blob/v1.0.5/puppet_forge.gemspec))
- C: `her 0.6.8` requires `activesupport  >= 3.0.0` ([reference](https://github.com/remiprev/her/blob/v0.6.8/her.gemspec))
- D: `activesupport 5.0.0.beta1` requires `ruby >= 2.2.2` ([reference](https://github.com/rails/rails/blob/v5.0.0.beta1/activesupport/activesupport.gemspec))

C was fixed in https://github.com/remiprev/her/issues/227, but not for version 0.6 which is very old.

Best would probably be to change A, and upgrade to puppet_forge 2?
Wdyt?

### PR DESCRIPTION
**Pull request by njam**
Closes #330

@carlossg please review

### CODE REVIEW

**Comment by JayH5** [comment]
An additional benefit of this is that requiring `activesupport` results in requiring `json` which means that on a clean machine you need to install the Ruby development headers to be able to compile the native extensions for `json`. With `puppet_forge` 2 (as used by `r10k`) this is not necessary.

**Comment by richdel** [comment]
+1 for this, can't create any new VMs whilst this issue persists, receiving the following error:

```
sudo gem install --no-ri --no-rdoc librarian-puppet deep_merge
ERROR:  Error installing librarian-puppet:
        activesupport requires Ruby version >= 2.2.2.
Successfully installed deep_merge-1.0.1
1 gem installed
```

**Comment by njam** [comment]
@carlossg wdyt? Could you release a new version with this?

**Comment by gesinn-it** [comment]
+1

**Comment by Kriechi** [comment]
:+1:

**Comment by njam** [comment]
This repo seems to be unmaintained, so I'm moving this pull request to https://github.com/voxpupuli/librarian-puppet/pull/1

**Pull request closed without merging**
